version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=gestion_heures
      - DB_USER=root
      - DB_PASSWORD=Lionel@02407151
      - JWT_SECRET=Lionel@02407151
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Lionel@02407151
      - MYSQL_DATABASE=gestion_heures
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: